# Generated by Django 5.0.7 on 2024-07-19 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onetoone', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurtant',
            old_name='numbre_of_employeers',
            new_name='number_of_employees',
        ),
    ]
