# Generated by Django 5.0.7 on 2024-07-20 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_code',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='zip_code',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='salary',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
