# Generated by Django 5.0.7 on 2024-07-16 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0003_rename_comments_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='nombre',
            new_name='name',
        ),
    ]
