# Generated by Django 5.0.7 on 2024-07-20 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manytoone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='head_line',
            field=models.CharField(max_length=100),
        ),
    ]
